### ISSUE TITLE
Master "To Add" List - effect resources

### ISSUE THREAD

**Issue by chriscoyier** [h5bp/Effeckt.css#128]
- [ ] Add to modals http://tympanus.net/Development/PFold/index3.html
- [ ] Add to buttons http://tympanus.net/Development/CreativeButtons/
- Add to page transitions
  - [ ] http://tympanus.net/Development/PageTransitions/
  - [ ] http://lab.hakim.se/kontext/
- Add to list items 
  - [ ] http://sarasoueidan.com/blog/ui-transitions-creative-add-remove-effects-for-list-items/demo/index-6.html
  - [ ] http://i.imgur.com/jyvPoWU.gif
- [ ] Add to tabs section http://git.aaronlumsden.com/tabulous.js/
- [ ] Add to offscreen nav http://tympanus.net/Tutorials/YouTubeLeftSideMenu/
- [ ] Add header/footer section http://www.inserthtml.com/demo/header-animations/example-2/
- [ ] Add to page transitions http://dan-silver.github.io/ElementTransitions.js/
- Add a dropdown menu section 
  - [ ] http://codepen.io/soulrider911/pen/bJqkC
  - [ ] http://i.imgur.com/CJgMTNy.gif
- [ ] Add a lazyloading section http://tympanus.net/Development/GridLoadingEffects/index.html
- [x] Add a form elements section http://codepen.io/uquaisse/pen/Jqhte
- [x] Add a "shake" animation in modal section
- [ ] Add a tooltips section http://i.imgur.com/lndT6bV.gif

**Comment by iamulya** [comment]
A new slide-in effect that could be used for lists or other elements. Plunkr:

http://plnkr.co/edit/KelM15kELl1tMQvzsyGn?p=preview
