### ISSUE TITLE
Need tag for CDN

### ISSUE THREAD

**Issue by DaAwesomeP** [h5bp/Effeckt.css#155]
Hi,
I would like to add Effeckt.css to the free, open-source, ssl-enabled, super-fast CDN: [CDNjs](https://cdnjs.com/). It is hosted on the Cloudflare Servers and has a GitHub repo here: [cdnjs/cdnjs](https://github.com/cdnjs/cdnjs).

I was going to add Effect.css to CDNjs, but I saw that there are no tags. CDNjs requires a tag (e.g. "v1.0" or "1.0") for each library so that when a new library or update come out, the library can be re-uploaded without disturbing the older version which people might prefer or still use. Think of Google's CDN and how it incorporates version numbers into the jQuery URLs.

Would it be possible for a tag to be created? I know this isn't official yet, but I think "1.0.0" would do, and for every small release in the future could be "1.0.1", bigger releases would be "1.1.0", and a massive overhaul would be "2.0.0", etc. A basic version system. Of course, for beta and alpha stages, it could be "0.1.0", etc.

I know it might be a pain to keep up with, but I would be glad to help.

Thanks,
[DaAwesomeP](https://github.com/DaAwesomeP/)

**Comment by arthurvr** [comment]
Shouldn't we close this for the time being? This kind of things are more topic to discuss if we ever reach a 1.0.

**Comment by arthurvr** [comment]
Didn't hear any complaints so closing for the time being. Feel free to re-open when it makes sense.
