### ISSUE TITLE
Logo Boredom

### ISSUE THREAD

**Issue by grayghostvisuals** [h5bp/Effeckt.css#277]
While I was at ConvergeSE I doodled this.
![screenshot 2014-05-10 14 57 51](https://cloud.githubusercontent.com/assets/934322/2936832/06d91622-d875-11e3-9d5c-b8e0e9963810.png)

**Comment by arthurvr** [comment]
I like all of them, mainly the middle one. :+1: Maybe we should toy a little with the font though. Dunno but it looks a little old school. 

> Thanks everyone. I'll tinker some more and repost :)

You ever got to it? Would love to see where you can come up with.

**Comment by grayghostvisuals** [comment]
@arthurvr sadly no. Maybe someone else can take the lead here and finish up.

**Comment by nathan-hinshaw** [comment]
I'm happy to take a run at it.
