### ISSUE TITLE
New slideIn effect

### ISSUE THREAD

**Issue by hybridpro** [h5bp/Effeckt.css#302]
A new slide-in effect that could be used for lists or other elements. Plunkr:

http://plnkr.co/edit/KelM15kELl1tMQvzsyGn?p=preview

**Comment by arthurvr** [comment]
Mind posting this one in https://github.com/h5bp/Effeckt.css/issues/128? It's the place where we keep all effects we ever want to add so I guess it makes more sense over there.

**Comment by nathan-hinshaw** [comment]
Just as an aside the animation--as presented in that Plunkr--is pretty browser specific, so something like Firefox is left out in the cold.
