### ISSUE TITLE
automatically deploy gh-pages branch using travis

### ISSUE THREAD

**Issue by arthurvr** [h5bp/Effeckt.css#306]
Right now we use [a grunt task](https://github.com/h5bp/Effeckt.css/blob/master/Gruntfile.js#L160) to push the gh-pages branch on every commit. Complicated workflow and a waste of time.

In other h5bp repositories we've been using the @h5bp-bot and [its script](https://github.com/h5bp-bot/scripts/blob/master/update_site_branch.sh) for that, which turns out to be a nice workflow. You can see an example of the setup in the [HTML5 Please repo](https://github.com/h5bp/html5please/blob/master/.travis.yml#L6). It also makes sure builds that fail don't get deployed.

**Comment by grayghostvisuals** [comment]
Feel free to implement this better workflow since you know it already. :+1:

**Comment by WellingGuzman** [comment]
@arthurvr let me know whether you are working on it?

**Comment by arthurvr** [comment]
@WellingGuzman I will work on it :)

**Comment by arthurvr** [comment]
Just as a status update: I never granted this much priority as the project was pretty inactive lately. Still happy to pick it up if the project gets a little more active again.

**Comment by WellingGuzman** [comment]
@arthurvr yes, please. let's wake this bad boy up.
