### ISSUE TITLE
Remove blur modal effect

### ISSUE THREAD

**Issue by davidyezsetz** [h5bp/Effeckt.css#308]
Not performing at 60fps

**Comment by arthurvr** [comment]
Yeah it's not one of our most performant ones, I agree. Let's take a look at making it better before actually removing it, though :)

**Comment by davidyezsetz** [comment]
I recently dug into this one a bit, because we wanted to use it in a project. We quickly shied away because the fullscreen blur is to heavy on an average machine. I'd be happy to be proven wrong, but I think currently this effect can't be implemented at 60fps.

As you can see the paint alone is far over the limit.
![screen shot 2015-05-17 at 15 49 22](https://cloud.githubusercontent.com/assets/1818395/7670640/8f9c1dc2-fcac-11e4-9f22-334f871c4d66.png)

**Comment by WellingGuzman** [comment]
This have been a heavy animation, let's see if we can improve it before remove it like @arthurvr said.

**Comment by davidyezsetz** [comment]
I'd love to see you succeed, but with a full screen blur I have my doubts.

**Comment by WellingGuzman** [comment]
@davidyezsetz yeah, like I said it's a heavy and always have been heavy, probably there's some cool light ways, I'll try if not, we can remove it until it can be done it nicely.
