### ISSUE TITLE
Can we use bower instead of having jQuery checked in to this repo?

### ISSUE THREAD

**Issue by ShashankaNataraj** [h5bp/Effeckt.css#309]
I find jQuery 2.1.1 checked in under the libs folder. Not necessary?

**Comment by arthurvr** [comment]
Yes we can! :+1: Just make sure we don't break the sourcemaps and the `grunt deploy` stays running fine.

**Comment by ShashankaNataraj** [comment]
I will take this one step at a time. Let me add a bower file first and we will take it from there.

**Comment by ShashankaNataraj** [comment]
My pull request has been submitted for this enhancement, I have tested the grunt:demo task on my local system and see that everything works as it should. Please have a look and let me know if I missed anything.

Also, the one thing remaining for this task to actually be complete is to add an entry in the wiki noting the bower change :)

**Comment by ShashankaNataraj** [comment]
@arthurvr , Any suggestions on this pull request?

**Comment by arthurvr** [comment]
Closing as the pull request landed. Thanks for the hard work, @ShashankaNataraj.
