### ISSUE TITLE
Remove jQuery functions as they are an overhead for something as simple as this library

### ISSUE THREAD

**Issue by ShashankaNataraj** [h5bp/Effeckt.css#312]
Update: Through general consensous, it has been decided that we want to remove jQuery functionality from this library.

Original issue:

As I see it, this library is heavily dependent on jQuery already

For example this line here: https://github.com/h5bp/Effeckt.css/blob/master/js/modules/modal.js#L41

So why are we using functions like these:

https://github.com/h5bp/Effeckt.css/blob/master/js/core.js#L43

I just tested this function in my browser after opening the demo page and the values returned by `Effeckt.prototype.getViewportHeight` and `$(window).height();` are exactly the same.

Do we even need functions like `Effeckt.prototype.getViewportHeight`? Can I remove functions like these since these add nothing new to already battle hardened jQuery functions?

**Comment by grayghostvisuals** [comment]
Sure. The actual syntax was something we agreed on when we first started the project. Since you seem to have motivation with this I would highly suggest you go through some old tracker issues to become more acquainted with the project and it's intentions :)

**Comment by arthurvr** [comment]
> Since you seem to have motivation with this I would highly suggest you go through some old tracker issues to become more acquainted with the project and it's intentions :)

Sure! Though be warned that many decisions from back 2 years ago might be worth it to reconsider.

**Comment by ShashankaNataraj** [comment]
Sure will do grayghostvisuals.

So can I raise a PR with this change?

**Comment by grayghostvisuals** [comment]
sure

**Comment by arthurvr** [comment]
@grayghostvisuals @ShashankaNataraj If we depend on jQuery we should really use it, I agree. Though, wouldn't it be appropriate to revision the decision to depend on jQuery one day? I like jQuery but effeckt's JavaScript looks rather easy so it's quite a big dependency.

**Comment by grayghostvisuals** [comment]
We should eliminate jQuery. No need for it.

**Comment by AaronLayton** [comment]
Agreed - jQuery is a massive overhead for something like this that just needs simple values and simple DOM interaction

I vote remove the jQuery references

**Comment by ShashankaNataraj** [comment]
ok, whats the final word on this @grayghostvisuals @arthurvr ?

**Comment by grayghostvisuals** [comment]
@ShashankaNataraj  remove

**Comment by ShashankaNataraj** [comment]
@grayghostvisuals @AaronLayton Have updated the title of this issue to make sense in this context instead of raising a new one!

**Comment by arthurvr** [comment]
Just to quickly clarify: I like jQuery (am even a team member over there). I just think such a dependency limits the amount of people able to use effeckt and our JavaScript isn't (and probably never will) be really in need of it.

**Comment by joshioo** [comment]
> am even a team member over there). 

@arthurvr changing documentation doesn't make you a valuable contributor so stop bragging ... you're just an arrogant faggot who like to comment like he knows something but in reality you don't faggot!!!

**Comment by AaronLayton** [comment]
![e31](https://cloud.githubusercontent.com/assets/694964/7934303/16b5d06e-091e-11e5-8b76-181e9b810a0e.jpg)


I think we are all in agreeance - lets remove and get a PR up

**Comment by ShashankaNataraj** [comment]
@grayghostvisuals @arthurvr @AaronLayton I see references to [Modernizr](https://github.com/h5bp/Effeckt.css/blob/master/js/core.js#L5) too! Are you guys in agreement that we need to remove references to Modernizr too?

**Comment by grayghostvisuals** [comment]
@ShashankaNataraj You can discuss that in another ticket.
