### ISSUE TITLE
Remove Modernizr references

### ISSUE THREAD

**Issue by ShashankaNataraj** [h5bp/Effeckt.css#315]
In [this ticket](https://github.com/h5bp/Effeckt.css/issues/312) we discussed that we wanted to remove jQuery from the core altogether.

Why then, do we have references to Modernizr in [code](https://github.com/h5bp/Effeckt.css/blob/master/js/core.js#L5)? If jQuery is heavy for a library of this purpose, isn't Modernizr heavy too?

**Comment by arthurvr** [comment]
I think it's worth mentioning that the code you linked up doesn't really require modernizr. If it's not in the global scope, it will just use defaults.

> Why then, do we have references to Modernizr in code? If jQuery is heavy for a library of this purpose, isn't Modernizr heavy too?

That's not the question we should be asking. Where are we using it for and is that easy to replace with an alternative approach?

**Comment by arthurvr** [comment]
> Where are we using it for and is that easy to replace with an alternative approach?

What does the rest think?

**Comment by AaronLayton** [comment]
I would remove modernizr - for the same reasons as jQuery.

Lets see where we are using it already and take it from there

**Comment by WellingGuzman** [comment]
We only used Modernzr to detect wether or not is a touch device and to get the prefixed `transition` property and jQuery is mostly as element selector and events.

I vote for removing it.

**Comment by ShashankaNataraj** [comment]
Alright, Im putting dibs on doing this task too :) I will be taking this one up as well, as soon as I get the JSCRC file done on the other issue.

**Comment by githubgmq** [comment]
@ShashankaNataraj Is there a schedule to remove Modernizr and jquery?

**Comment by ShashankaNataraj** [comment]
@githubgmq No.
