### ISSUE TITLE
Update the version of Effeckt on npm

### ISSUE THREAD

**Issue by arthurvr** [h5bp/Effeckt.css#316]
We have an official [npm package](https://www.npmjs.com/package/effeckt) but it's really outdated. Let's bump it. 

@paulirish Mind adding me (or anyone else from @h5bp/effeckt-css) to the npm package so we can bump the version?

**Comment by AaronLayton** [comment]
@paulirish I was on but seem to have been removed?

**Comment by WellingGuzman** [comment]
to be honest, I didn't know we had a npm package.

**Comment by paulirish** [comment]
Not exactly what you're asking for but i'm going to unpublish the npm package for now.

**Comment by arthurvr** [comment]
:+1:
