### ISSUE TITLE
Archiving this repo?

### ISSUE THREAD

**Issue by roblarsen** [h5bp/Effeckt.css#324]
I'm thinking of archiving this repo. I knew nothing of it when it was a living thing and no nothing of it now. I'm just going through the repos in the h5bp organization and trying to make sense of what needs nurturing and amplification.  

Archiving this repo means it would still be here, it would just be ready-only. 

Alternatively, if someone thinks there's something worth revisiting here and wants to try to pick up where we left off many years ago, we can talk about that as well. 

I'll monitor comments here and will make a decisions about what to do in a week or so.

**Comment by paulirish** [comment]
archiving sgtm.

**Comment by roblarsen** [comment]
Thanks, Paul.

I'm going to go ahead with the plan to archive this repo.

**Comment by roblarsen** [comment]
Thanks everyone!
